obj = open('sieu quan trong.txt', 'w')
obj.write("Chao mung cac ban den voi khoa CNTT")
obj.close()
obj1 = open('sieu quan trong.txt', 'r')
s = obj1.read()
print(s)
obj1.close()
obj2 = open('sieu quan trong.txt', 'r')
s1 = obj2.read(20)
print(s1)
obj2.close()